name: CRLF Check

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]

jobs:
    build:
        name: CRLF Check
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: recursive

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Check for CRLF
              run: python3 Tools/check_crlf.py
